"""Add fargate arn

Revision ID: e5acf335b645
Revises: ccf63450ffc1
Create Date: 2024-11-26 14:47:41.225465

"""

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision = "e5acf335b645"
down_revision = "ccf63450ffc1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("jobs", sa.Column("fargate_task_arn", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("jobs", "fargate_task_arn")
    # ### end Alembic commands ###
